name: Add external contributor
description: Request to be added to the organization as an external contributor.
body:
  - type: input
    id: github-handle
    attributes:
      label: GitHub Handle
      description: Enter your GitHub username.
      placeholder: octocat
    validations:
      required: true
