name: Create repository self-service
labels:
 - "create-repository"
title: "Creating a demo repository for the logged in user"
description: |
  Request a new repository via self-service workflow input.
  The repository will be named **devopsdays.demo.YOUR_USERNAME**.
  Choose the technology stack below.
body:
  - type: input
    id: password
    attributes:
      label: "Password:"
      description: Enter the access password to use this self-service.
    validations:
      required: true
  - type: dropdown
    id: technology
    attributes:
      label: Technology
      description: Select the technology to use for the new repository.
      options:
        - Docker
        - Maven
    validations:
      required: true